# Main liguage of the project
language:
    python

# Versions of python wich your project accepted
python:
    - "3.5"

# Setting Django environment
env:
    - DJANGO_VERSION=1.11.1


# Install some packages before install django
install:

    - pip install Django

    - pip install nose

    - pip install coverage

    - pip install flake8

    - pip install factory_boy

    - pip install codecov



script:
    - python manage.py migrate
    - coverage run --source='.' manage.py test rooms
    - coverage report
    - codecov

